# Generated by Django 4.2.11 on 2024-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_product_show_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_boilerdata',
            name='formType',
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='boiler_type',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='job_type',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='power_usage',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='property_type',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
    ]
