# Generated by Django 4.2.11 on 2024-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_remove_q_boilerdata_formtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_evdata',
            name='formType',
        ),
        migrations.RemoveField(
            model_name='q_heatpumps',
            name='formType',
        ),
        migrations.RemoveField(
            model_name='q_homesecurity',
            name='formType',
        ),
        migrations.RemoveField(
            model_name='q_infraredheat',
            name='formType',
        ),
        migrations.RemoveField(
            model_name='q_solar',
            name='formType',
        ),
        migrations.RemoveField(
            model_name='q_window',
            name='formType',
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='boiler_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='job_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='power_usage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_boilerdata',
            name='property_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='car_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='charger_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='full_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='installation_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='ownership_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='parking_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_evdata',
            name='post_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Q_FormType',
        ),
    ]
