# Generated by Django 4.2.11 on 2024-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_remove_q_evdata_formtype_remove_q_heatpumps_formtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_heatpumps',
            name='avilable_space',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='full_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='heat_pump_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='heating_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='insulation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='loaction_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='owenership_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='post_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='power_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='property_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_heatpumps',
            name='radiators',
            field=models.CharField(max_length=255),
        ),
    ]
