# Generated by Django 4.2.11 on 2024-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_q_heatpumps_avilable_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_homesecurity',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_homesecurity',
            name='full_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_homesecurity',
            name='ownership',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_homesecurity',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_homesecurity',
            name='post_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='q_homesecurity',
            name='residency',
            field=models.CharField(max_length=255),
        ),
    ]
