# Generated by Django 4.2.11 on 2024-05-09 15:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_q_infraredheat_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='details',
            new_name='package_details',
        ),
        migrations.AddField(
            model_name='packages',
            name='package_summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='q_window',
            name='delivery',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_window',
            name='glazing_for',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_window',
            name='number_of_window',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='q_window',
            name='ownership',
            field=models.CharField(max_length=255),
        ),
    ]
