# Generated by Django 4.2.11 on 2024-05-25 06:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_q_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('experience_requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('job_post_date', models.DateField()),
                ('application_deadline', models.DateField()),
            ],
        ),
    ]
