# Generated by Django 4.2.11 on 2024-05-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='experience_requirements',
            new_name='job_resposiblities',
        ),
    ]
