# Generated by Django 4.2.11 on 2024-05-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_rename_experience_requirements_jobs_job_resposiblities'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('indentification_card', models.FileField(blank=True, null=True, upload_to='media/application')),
                ('cv', models.FileField(blank=True, null=True, upload_to='media/application')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='media/application')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.jobs')),
            ],
        ),
    ]
