# Generated by Django 4.2.11 on 2024-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_type',
            field=models.CharField(choices=[('', 'Select Account Type'), ('Installer ', 'Installer '), ('Reseller', 'Reseller')], default='', max_length=10),
        ),
    ]
