# Generated by Django 4.2.11 on 2024-05-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_register_account_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
